-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgA0Jv+TOWpZr5ge9t
/1L57LdjXPXNQoYj9c9vMts5XUKgCgYIKoZIzj0DAQehRANCAAR+EpGcvr7UNWzT
i5wgeE9XE3RnWCtAEhyk8eTevRi+IV3xyqkZnhiGXa5CTvJlu0YjNWAR62+y3rEt
/kDjTXXQ
-----END PRIVATE KEY-----